spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://ec2-13-209-42-78.ap-northeast-2.compute.amazonaws.com:3306/mydb
    username: root
    password: 1234

  sql:
    init:
      mode: always
      encoding: utf-8

  h2:
    console:
      enabled: true
      path: /h2-console
